### ISSUE TITLE
error when testing show and update model

### ISSUE THREAD

**Issue by jamesbright** [Oladunsi/AirBnB_clone#3]
an error shows up when testing show and update of console.py, please check and get it fixed.
the error details is below

(hbnb) show BaseModel
Traceback (most recent call last):
  File "./console.py", line 157, in <module>
    HBNBCommand().cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "./console.py", line 62, in do_show
    if not self.verify_id(line):  # if dis returns anything not True
TypeError: verify_id() takes 1 positional argument but 2 were given

**Comment by jamesbright** [comment]
well done on the fix.
